"""initial schema

Revision ID: c9e6df993b97
Revises: 
Create Date: 2026-10-01 17:59:34.860612
"""
from alembic import op
import sqlalchemy as sa


revision = 'c9e6df993b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('MOVIE', 'CONCERT', 'COMEDY', 'THEATRE', 'OTHER', name='event_type'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='event_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_index('ix_venues_city_lower', 'venues', [sa.literal_column('lower(city)')], unique=False)
    op.create_table('screens',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_screens_venue_id_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screens'))
    )
    op.create_index(op.f('ix_screens_venue_id'), 'screens', ['venue_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('seats',
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('row_label', sa.String(length=5), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('REGULAR', 'PREMIUM', 'RECLINER', name='seat_type'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_seats_screen_id_screens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('screen_id', 'row_label', 'seat_number', name=op.f('uq_seats_screen_id'))
    )
    op.create_index(op.f('ix_seats_screen_id'), 'seats', ['screen_id'], unique=False)
    op.create_table('shows',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='show_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_shows_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_shows_screen_id_screens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shows'))
    )
    op.create_index(op.f('ix_shows_event_id'), 'shows', ['event_id'], unique=False)
    op.create_index('ix_shows_screen_id_start_time', 'shows', ['screen_id', 'start_time'], unique=False)
    op.create_index('ix_shows_status_start_time', 'shows', ['status', 'start_time'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='booking_status'), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_bookings_show_id_shows')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('booking_number', name=op.f('uq_bookings_booking_number'))
    )
    op.create_index(op.f('ix_bookings_show_id'), 'bookings', ['show_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('show_seats',
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='show_seat_status'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_show_seats_seat_id_seats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_show_seats_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_seats')),
    sa.UniqueConstraint('show_id', 'seat_id', name=op.f('uq_show_seats_show_id'))
    )
    op.create_index('ix_show_seats_show_id_status', 'show_seats', ['show_id', 'status'], unique=False)
    op.create_table('booking_seats',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('show_seat_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_seats_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], name=op.f('fk_booking_seats_show_seat_id_show_seats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_seats')),
    sa.UniqueConstraint('show_seat_id', name=op.f('uq_booking_seats_show_seat_id'))
    )
    op.create_index(op.f('ix_booking_seats_booking_id'), 'booking_seats', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_payments_transaction_id'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_table('receipts',
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_receipts_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_receipts_payment_id')),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_receipts_receipt_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_booking_seats_booking_id'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index('ix_show_seats_show_id_status', table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_show_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_shows_status_start_time', table_name='shows')
    op.drop_index('ix_shows_screen_id_start_time', table_name='shows')
    op.drop_index(op.f('ix_shows_event_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_seats_screen_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_screens_venue_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index('ix_venues_city_lower', table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
